### ISSUE TITLE
Multiple Languages

### ISSUE THREAD

**Issue by juanbeniteza** [Wisp-CMS/nextjs-blog-cms-wisp#6]
Let's say I have my blog already serving content in English, now I want to translate my posts to Spanish so I can reach a broader audience, how can I modify this code so that I have a "sub blog" only in Spanish, for example www.my-blog.com/es/

To know if a post is in Spanish or English I plan to tag them accordingly 

The translation of nav items and footer text are not important. 

Can the SEO be affected by doing this?

**Comment by yehjxraymond** [comment]
Hi, you can see this guide on intl where you can route all paths under /es/ to the Spanish version. It will be best to use 2 different wisp blog to serve the separate content, with each having its own blog ID and when you are on the intl version to serve a different blog ID.

https://nextjs.org/docs/app/building-your-application/routing/internationalization
